const MESES = ["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
const APARTAMENTOS_PADRAO = ["101","101 Fundos","201","201 Sala","201 Fundos","301","301 Sala","301 Fundos"];
const FIXOS = { taxaCondominio:160, emitente:"Gabriel Brito Cirilo", cidade:"Rio de Janeiro", rua:"Rua Glaziou, 30", bairroUf:"Pilares - RJ", cep:"20750-010", aptoIsentoPadrao:"101 Fundos", logoPath:"logo.png" };
const STORAGE = { apartments:"cond_apartments_v4", receipts:"cond_receipts_v4", expenses:"cond_expenses_v4", seq:"cond_receipt_seq_v4", settings:"cond_settings_v4", logo:"cond_logo_cache_v4" };
const OLD = { apartments:"cond_apartments_v3", receipts:"cond_receipts_v3", expenses:"cond_expenses_v3", seq:"cond_receipt_seq_v3" };
const state = { apartments:[], receipts:[], expenses:[], settings:{saldoInicial:0,saldoReal:0}, logoDataUrl:"" };
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
function saveJSON(k,v){localStorage.setItem(k,JSON.stringify(v));}
function loadJSON(k,f){try{const r=localStorage.getItem(k);return r?JSON.parse(r):f;}catch{return f;}}
function moneyToNumber(v){if(v===undefined||v===null)return 0; return Number(String(v).replace(/\./g,"").replace(",",".").replace(/[^\d.-]/g,""))||0;}
function numberToMoney(n){return (Number(n)||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});}
function numberToInput(n){return (Number(n)||0).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2});}
function uid(){return `id_${Date.now()}_${Math.random().toString(16).slice(2)}`;}
function pad(n,size=6){const s=String(n);return s.length>=size?s:"0".repeat(size-s.length)+s;}
function today(){const d=new Date();return {dia:d.getDate(),mes:d.getMonth(),ano:d.getFullYear()};}
function monthYearLabel(m,y){return `${MESES[Number(m)]}/${y}`;}
function enderecoCompleto(apto){return `${FIXOS.rua} — Apto ${apto} / ${FIXOS.bairroUf}`;}
function statusFromBalance(b){b=Number(b)||0;if(b>0)return b<FIXOS.taxaCondominio?"Parcial":"Em aberto"; if(b<0)return "Crédito"; return "Quitado";}
function aptById(id){return state.apartments.find(a=>a.id===id||a.name===id);}
function getSeq(){return Number(localStorage.getItem(STORAGE.seq)||localStorage.getItem(OLD.seq)||"0");}
function setSeq(n){localStorage.setItem(STORAGE.seq,String(n));}
function syncSeq(){let m=0;state.receipts.forEach(r=>{const n=Number(String(r.number||"").replace(/\D/g,""))||0;if(n>m)m=n;});if(m>getSeq())setSeq(m);}
function nextNumber(){syncSeq();return pad(getSeq()+1);} function consumeNumber(){syncSeq();const n=getSeq()+1;setSeq(n);return pad(n);}
function saveAll(){saveJSON(STORAGE.apartments,state.apartments);saveJSON(STORAGE.receipts,state.receipts);saveJSON(STORAGE.expenses,state.expenses);saveJSON(STORAGE.settings,state.settings);}
function migrate(){
  state.apartments=loadJSON(STORAGE.apartments,null)||loadJSON(OLD.apartments,[]);
  state.receipts=loadJSON(STORAGE.receipts,null)||loadJSON(OLD.receipts,[]);
  state.expenses=loadJSON(STORAGE.expenses,null)||loadJSON(OLD.expenses,[]);
  state.settings=loadJSON(STORAGE.settings,{saldoInicial:0,saldoReal:0});
  if(!state.apartments.length) state.apartments=APARTAMENTOS_PADRAO.map(n=>({id:n,name:n,residentName:"",balance:0,justification:"",exemptCondo:n===FIXOS.aptoIsentoPadrao}));
  APARTAMENTOS_PADRAO.forEach(n=>{ if(!state.apartments.find(a=>a.name===n||a.id===n)) state.apartments.push({id:n,name:n,residentName:"",balance:0,justification:"",exemptCondo:n===FIXOS.aptoIsentoPadrao}); });
  state.apartments=state.apartments.map(a=>({id:a.id||a.name,name:a.name||a.id,residentName:a.residentName||"",balance:Number(a.balance)||0,justification:a.justification||a.justificativa||"",exemptCondo:(a.name||a.id)===FIXOS.aptoIsentoPadrao?true:!!a.exemptCondo}));
  state.receipts=state.receipts.map(r=>({ id:r.id||uid(), number:r.number||pad(0), apartmentName:r.apartmentName||r.apto||"", residentName:r.residentName||r.name||"", year:Number(r.year)||today().ano, months:Array.isArray(r.months)?r.months.map(Number):[Number(r.month||today().mes)], referente:r.referente||"Condomínio", condoPerMonth:Number(r.condoPerMonth)||0, extraPerMonth:0, previousBalance:Number(r.previousBalance)||0, launchedNow:Number(r.launchedNow)||0, paidNow:Number(r.paidNow)||0, remainingBalance:Number(r.remainingBalance)||0, status:r.status||statusFromBalance(r.remainingBalance), issueDay:Number(r.issueDay)||today().dia, issueMonth:Number(r.issueMonth ?? today().mes), issueYear:Number(r.issueYear)||today().ano, createdAt:Number(r.createdAt)||Date.now() }));
  state.expenses=state.expenses.map(e=>({id:e.id||uid(),day:Number(e.day)||today().dia,month:Number(e.month)||today().mes,year:Number(e.year)||today().ano,category:e.category||"Outros",description:e.description||"",value:Number(e.value)||0,createdAt:Number(e.createdAt)||Date.now()}));
  recalcBalances(false); saveAll(); syncSeq();
}
function fillMonths(sel,all=false){sel.innerHTML=""; if(all) sel.append(new Option("Todos","-1")); MESES.forEach((m,i)=>sel.append(new Option(m,String(i))));}
function fillDays(sel){sel.innerHTML=""; for(let i=1;i<=31;i++)sel.append(new Option(String(i),String(i)));}
function fillApartmentSelect(){const sel=qs("#recApto"); sel.innerHTML=""; state.apartments.slice().sort((a,b)=>a.name.localeCompare(b.name)).forEach(a=>sel.append(new Option(a.name,a.id)));}
function buildMonthChecklist(){const box=qs("#monthChecklist"); box.innerHTML=""; MESES.forEach((m,i)=>{const l=document.createElement("label");l.className="month-item";l.innerHTML=`<input type="checkbox" value="${i}" class="month-check"> <span>${m}</span>`;box.appendChild(l);});}
function selectedMonths(){return qsa(".month-check:checked").map(e=>Number(e.value)).sort((a,b)=>a-b);}
function switchTab(tab){qsa(".sidebtn").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));qsa(".panel").forEach(p=>p.classList.add("hidden"));qs(`#tab-${tab}`).classList.remove("hidden");}
function loadDefaults(){const t=today(); fillApartmentSelect(); fillMonths(qs("#despMes")); fillMonths(qs("#histMes"),true); fillDays(qs("#despDia")); buildMonthChecklist(); qs("#recNumero").value=nextNumber(); qs("#recAnoRef").value=t.ano; qs("#recDiaAtual").value=t.dia; qs("#despDia").value=t.dia; qs("#despMes").value=t.mes; qs("#despAno").value=t.ano; qs("#histAno").value=t.ano; qs("#histMes").value="-1"; qs("#saldoInicial").value=numberToInput(state.settings.saldoInicial); qs("#saldoReal").value=numberToInput(state.settings.saldoReal); const c=qsa(".month-check"); if(c[t.mes])c[t.mes].checked=true; handleApartmentChange();}
function computeReceiptData(){const apt=aptById(qs("#recApto").value); if(!apt)return null; const months=selectedMonths(), year=Number(qs("#recAnoRef").value)||today().ano, day=Number(qs("#recDiaAtual").value)||today().dia; const includeCondo=qs("#ckCondo").checked; const condoPerMonth=includeCondo?(apt.exemptCondo?0:FIXOS.taxaCondominio):0; const previousBalance=Number(apt.balance)||0; const launchedNow=months.length*condoPerMonth; const paidNow=moneyToNumber(qs("#recPagoAgora").value); const remainingBalance=previousBalance+launchedNow-paidNow; const referente=includeCondo?"Condomínio":"Pagamento / baixa"; return {apt,months,year,day,includeCondo,condoPerMonth,extraPerMonth:0,previousBalance,launchedNow,paidNow,remainingBalance,status:statusFromBalance(remainingBalance),referente,name:qs("#recNome").value.trim()};}
function refreshReceiptPreview(){const d=computeReceiptData(); if(!d)return; qs("#enderecoLinha").textContent=enderecoCompleto(d.apt.name); qs("#recCondominio").value=numberToInput(d.condoPerMonth); qs("#recSaldoAnterior").value=numberToMoney(d.previousBalance); qs("#recTotalLancado").value=numberToMoney(d.launchedNow); qs("#recSaldoRestante").value=numberToMoney(d.remainingBalance); qs("#recSituacao").value=d.status; const refs=d.months.length?d.months.map(m=>monthYearLabel(m,d.year)).join(", "):"Nenhum mês selecionado"; const linhas=[`Recebido de: ${d.name||"__________________________"}`,`Endereço: ${enderecoCompleto(d.apt.name)}`,`CEP: ${FIXOS.cep}`,"",`Referente a: ${d.referente}`,`Mês/Referência: ${refs}`,"","Valores recebidos:"]; if(d.includeCondo)linhas.push(`Condomínio: ${numberToMoney(d.condoPerMonth*d.months.length)}`); linhas.push("",`TOTAL: ${numberToMoney(d.paidNow)}`); if(d.previousBalance>0||d.remainingBalance>0){linhas.push("",`Saldo anterior: ${numberToMoney(d.previousBalance)}`,`Valor pago: ${numberToMoney(d.paidNow)}`,`Saldo restante: ${numberToMoney(d.remainingBalance)}`);} linhas.push("",`${FIXOS.cidade}, dia ${d.day} de ${MESES[today().mes]} de ${today().ano}`,"",`Emitente: ${FIXOS.emitente}`); qs("#recPreview").textContent=linhas.join("\n");}
function handleApartmentChange(){const apt=aptById(qs("#recApto").value); if(!apt)return; qs("#recCondominio").value=numberToInput(apt.exemptCondo?0:FIXOS.taxaCondominio); if(!qs("#recNome").value) qs("#recNome").value=apt.residentName||""; refreshReceiptPreview();}
function saveReceipt(){const d=computeReceiptData(); if(!d)return; if(!d.name)return alert("Digite o nome do morador/proprietário."); if(!d.months.length)return alert("Selecione pelo menos 1 mês."); if(!d.includeCondo && !d.paidNow)return alert("Marque Condomínio ou informe um valor pago para baixa."); const editId=qs("#editingReceiptId").value; let receipt={id:editId||uid(),number:editId?(state.receipts.find(r=>r.id===editId)||{}).number:consumeNumber(),apartmentName:d.apt.name,residentName:d.name,year:d.year,months:d.months,referente:d.referente,condoPerMonth:d.condoPerMonth,extraPerMonth:0,previousBalance:0,launchedNow:d.launchedNow,paidNow:d.paidNow,remainingBalance:0,status:"",issueDay:d.day,issueMonth:today().mes,issueYear:today().ano,createdAt:editId?(state.receipts.find(r=>r.id===editId)||{}).createdAt||Date.now():Date.now()}; if(editId) state.receipts=state.receipts.map(r=>r.id===editId?receipt:r); else state.receipts.push(receipt); recalcBalances(false); saveAll(); renderAll(); generateReceiptPDF(state.receipts.find(r=>r.id===receipt.id)); clearReceiptForm();}
function clearReceiptForm(){qs("#editingReceiptId").value=""; qs("#btnGerarRecibo").textContent="Gerar recibo e salvar"; qs("#recNumero").value=nextNumber(); qs("#recPagoAgora").value="0,00"; refreshReceiptPreview();}
function recalcBalances(show=true){state.apartments.forEach(a=>a.balance=0); state.receipts.sort((a,b)=>(a.createdAt||0)-(b.createdAt||0)).forEach(r=>{const apt=state.apartments.find(a=>a.name===r.apartmentName||a.id===r.apartmentName); if(!apt)return; const prev=Number(apt.balance)||0; r.previousBalance=prev; r.condoPerMonth=apt.exemptCondo?0:Number(r.condoPerMonth)||0; r.launchedNow=(r.months||[]).length*(Number(r.condoPerMonth)||0); r.remainingBalance=prev+r.launchedNow-(Number(r.paidNow)||0); r.status=statusFromBalance(r.remainingBalance); apt.balance=r.remainingBalance; if(r.residentName)apt.residentName=r.residentName; }); const isento=state.apartments.find(a=>a.name===FIXOS.aptoIsentoPadrao); if(isento){isento.exemptCondo=true; if(isento.balance<0){} } saveAll(); if(show)alert("Histórico recalculado com sucesso.");}
function renderApartments(){const tb=qs("#tbodyApartamentos"); tb.innerHTML=""; state.apartments.slice().sort((a,b)=>a.name.localeCompare(b.name)).forEach(a=>{const tr=document.createElement("tr"); tr.innerHTML=`<td>${a.name}</td><td><input type="text" value="${a.residentName||""}" data-nome="${a.id}"></td><td><input type="text" value="${numberToInput(a.balance)}" data-saldo="${a.id}"></td><td><input type="text" value="${a.justification||""}" data-just="${a.id}"></td><td><input type="text" value="0,00" data-pagav="${a.id}"></td><td><input type="checkbox" data-isento="${a.id}" ${a.exemptCondo?"checked":""} ${a.name===FIXOS.aptoIsentoPadrao?"disabled":""}></td><td class="actions"><button class="linkbtn" data-saveapt="${a.id}">Salvar</button><button class="linkbtn" data-payapt="${a.id}">Dar baixa</button></td>`; tb.appendChild(tr);}); tb.querySelectorAll("[data-saveapt]").forEach(b=>b.onclick=()=>{const a=aptById(b.dataset.saveapt); if(!a)return; a.residentName=tb.querySelector(`[data-nome="${a.id}"]`).value.trim(); a.balance=moneyToNumber(tb.querySelector(`[data-saldo="${a.id}"]`).value); a.justification=tb.querySelector(`[data-just="${a.id}"]`).value.trim(); a.exemptCondo=a.name===FIXOS.aptoIsentoPadrao?true:tb.querySelector(`[data-isento="${a.id}"]`).checked; saveAll(); renderAll();}); tb.querySelectorAll("[data-payapt]").forEach(b=>b.onclick=()=>{const a=aptById(b.dataset.payapt); const val=moneyToNumber(tb.querySelector(`[data-pagav="${a.id}"]`).value); if(!val)return alert("Digite o valor pago."); state.receipts.push({id:uid(),number:consumeNumber(),apartmentName:a.name,residentName:a.residentName||"",year:today().ano,months:[today().mes],referente:"Pagamento avulso / baixa",condoPerMonth:0,extraPerMonth:0,previousBalance:a.balance,launchedNow:0,paidNow:val,remainingBalance:a.balance-val,status:statusFromBalance(a.balance-val),issueDay:today().dia,issueMonth:today().mes,issueYear:today().ano,createdAt:Date.now()}); recalcBalances(false); renderAll();});}
function setDefaultExpenseValue(){const c=qs("#despCat").value; if(c==="Zelador (Tião)")qs("#despValor").value="250,00"; if(c==="Material limpeza")qs("#despValor").value="50,00";}
function saveExpense(){const id=qs("#editingExpenseId").value; const value=moneyToNumber(qs("#despValor").value); if(!value)return alert("Digite um valor válido."); const e={id:id||uid(),day:Number(qs("#despDia").value),month:Number(qs("#despMes").value),year:Number(qs("#despAno").value),category:qs("#despCat").value,description:qs("#despDesc").value.trim(),value,createdAt:id?(state.expenses.find(x=>x.id===id)||{}).createdAt||Date.now():Date.now()}; if(id)state.expenses=state.expenses.map(x=>x.id===id?e:x); else state.expenses.push(e); saveAll(); clearExpenseForm(); renderAll();}
function clearExpenseForm(){qs("#editingExpenseId").value=""; qs("#btnAddDesp").textContent="Salvar despesa"; qs("#despValor").value=""; qs("#despDesc").value="";}
function renderExpenses(){const tb=qs("#tbodyDespesas"); tb.innerHTML=""; state.expenses.slice().sort((a,b)=>b.createdAt-a.createdAt).forEach(e=>{const tr=document.createElement("tr"); tr.innerHTML=`<td>${String(e.day).padStart(2,"0")}/${String(e.month+1).padStart(2,"0")}/${e.year}</td><td>${e.category}</td><td>${e.description||""}</td><td>${numberToMoney(e.value)}</td><td class="actions"><button class="linkbtn" data-expdf="${e.id}">PDF</button><button class="linkbtn" data-expedit="${e.id}">Editar</button><button class="linkbtn danger" data-expdel="${e.id}">Excluir</button></td>`; tb.appendChild(tr);}); tb.querySelectorAll("[data-expdel]").forEach(b=>b.onclick=()=>{if(confirm("Excluir esta despesa?")){state.expenses=state.expenses.filter(e=>e.id!==b.dataset.expdel);saveAll();renderAll();}}); tb.querySelectorAll("[data-expedit]").forEach(b=>b.onclick=()=>{const e=state.expenses.find(x=>x.id===b.dataset.expedit); if(!e)return; qs("#editingExpenseId").value=e.id; qs("#despDia").value=e.day; qs("#despMes").value=e.month; qs("#despAno").value=e.year; qs("#despCat").value=e.category; qs("#despValor").value=numberToInput(e.value); qs("#despDesc").value=e.description||""; qs("#btnAddDesp").textContent="Atualizar despesa";}); tb.querySelectorAll("[data-expdf]").forEach(b=>b.onclick=()=>generateExpensePDF(state.expenses.find(e=>e.id===b.dataset.expdf)));}
function histFilter(){const y=Number(qs("#histAno").value)||null; const mr=Number(qs("#histMes").value); return {year:y,month:mr>=0?mr:null};}
function filteredReceipts(){const {year,month}=histFilter(); return state.receipts.filter(r=>(!year||r.year===year)&&(month===null||(r.months||[]).includes(month)));}
function filteredExpenses(){const {year,month}=histFilter(); return state.expenses.filter(e=>(!year||e.year===year)&&(month===null||e.month===month));}
function totals(receipts=state.receipts,expenses=state.expenses){const rec=receipts.reduce((s,r)=>s+Number(r.paidNow||0),0); const desp=expenses.reduce((s,e)=>s+Number(e.value||0),0); const esp=Number(state.settings.saldoInicial||0)+rec-desp; const real=Number(state.settings.saldoReal||0); const dif=real-esp; return {rec,desp,esp,real,dif};}
function renderHistory(){const rec=filteredReceipts(), exp=filteredExpenses(), t=totals(rec,exp); qs("#histTotais").innerHTML=`<div><b>Total recebido:</b> ${numberToMoney(t.rec)}</div><div><b>Total despesas:</b> ${numberToMoney(t.desp)}</div><div><b>Saldo do período:</b> ${numberToMoney(t.rec-t.desp)}</div>`; const tb=qs("#tbodyHistorico"); tb.innerHTML=""; rec.slice().sort((a,b)=>b.createdAt-a.createdAt).forEach(r=>{const tr=document.createElement("tr"); const ref=(r.months||[]).map(m=>monthYearLabel(m,r.year)).join(", "); tr.innerHTML=`<td>${r.number}</td><td>${ref}</td><td>${r.apartmentName}</td><td>${r.residentName}</td><td>${numberToMoney(r.paidNow)}</td><td>${numberToMoney(r.remainingBalance)}</td><td>${String(r.issueDay).padStart(2,"0")}/${String(r.issueMonth+1).padStart(2,"0")}/${r.issueYear}</td><td class="actions"><button class="linkbtn" data-pdf="${r.id}">PDF</button><button class="linkbtn" data-edit="${r.id}">Editar</button><button class="linkbtn" data-copy="${r.id}">Refazer</button><button class="linkbtn danger" data-del="${r.id}">Excluir</button></td>`; tb.appendChild(tr);}); tb.querySelectorAll("[data-pdf]").forEach(b=>b.onclick=()=>generateReceiptPDF(state.receipts.find(r=>r.id===b.dataset.pdf))); tb.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{if(confirm("Excluir este recibo? O saldo será recalculado.")){state.receipts=state.receipts.filter(r=>r.id!==b.dataset.del);recalcBalances(false);renderAll();}}); tb.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>loadReceiptForm(state.receipts.find(r=>r.id===b.dataset.edit),true)); tb.querySelectorAll("[data-copy]").forEach(b=>b.onclick=()=>loadReceiptForm(state.receipts.find(r=>r.id===b.dataset.copy),false));}
function loadReceiptForm(r,edit){if(!r)return; switchTab("recibo"); qs("#editingReceiptId").value=edit?r.id:""; qs("#recNumero").value=edit?r.number:nextNumber(); qs("#recApto").value=(aptById(r.apartmentName)||{}).id||r.apartmentName; qs("#recNome").value=r.residentName||""; qs("#recAnoRef").value=r.year; qs("#recDiaAtual").value=r.issueDay; qs("#ckCondo").checked=(Number(r.condoPerMonth)||0)>0||r.referente.includes("Condomínio"); qs("#recPagoAgora").value=numberToInput(r.paidNow||0); qsa(".month-check").forEach(c=>c.checked=(r.months||[]).includes(Number(c.value))); qs("#btnGerarRecibo").textContent=edit?"Atualizar recibo":"Refazer como novo recibo"; refreshReceiptPreview();}
function renderPrestacao(){const t=totals(); const cls=t.dif>=0?"positive":"negative"; qs("#prestacaoResumo").innerHTML=`<div><b>Saldo inicial:</b> ${numberToMoney(state.settings.saldoInicial)}</div><div><b>Total recebido:</b> ${numberToMoney(t.rec)}</div><div><b>Total despesas:</b> ${numberToMoney(t.desp)}</div><div><b>Saldo esperado:</b> ${numberToMoney(t.esp)}</div><div><b>Saldo real:</b> ${numberToMoney(t.real)}</div><div><b>Diferença:</b> <span class="${cls}">${numberToMoney(t.dif)} — ${t.dif>=0?"🟢 POSITIVO":"🔴 NEGATIVO"}</span></div><hr><div><b>Quanto deveria existir:</b> ${numberToMoney(t.esp)}</div><div><b>Quanto existe:</b> ${numberToMoney(t.real)}</div><div><b>${t.dif<0?"Quanto falta":"Quanto sobrou"}:</b> ${numberToMoney(Math.abs(t.dif))}</div>`;}
async function loadLogoDataUrl(){if(state.logoDataUrl)return state.logoDataUrl; const cached=localStorage.getItem(STORAGE.logo); if(cached&&cached.startsWith("data:image/")){state.logoDataUrl=cached;return cached;} try{const res=await fetch(FIXOS.logoPath,{cache:"no-store"}); const blob=await res.blob(); const dataUrl=await new Promise((resolve,reject)=>{const rd=new FileReader();rd.onload=()=>resolve(rd.result);rd.onerror=reject;rd.readAsDataURL(blob);}); state.logoDataUrl=dataUrl; localStorage.setItem(STORAGE.logo,dataUrl); return dataUrl;}catch{return "";}}
function addLogo(doc,data){if(!data)return 18; try{const w=28,h=28,x=(doc.internal.pageSize.getWidth()-w)/2; doc.addImage(data,data.startsWith("data:image/jpeg")?"JPEG":"PNG",x,10,w,h); return 44;}catch{return 18;}}
function header(doc,title,y){doc.setFont("helvetica","bold");doc.setFontSize(14);doc.text(title,14,y);doc.setFont("helvetica","normal");doc.setFontSize(10);doc.text(`${FIXOS.rua} / ${FIXOS.bairroUf} — CEP ${FIXOS.cep} — ${FIXOS.cidade}/RJ`,14,y+6);doc.line(14,y+9,196,y+9);return y+20;}
async function generateReceiptPDF(r){if(!r)return; const {jsPDF}=window.jspdf; const doc=new jsPDF({unit:"mm",format:"a4"}); const logo=await loadLogoDataUrl(); let y=header(doc,`RECIBO Nº ${r.number}`,addLogo(doc,logo)); doc.setFontSize(12); doc.text(`Recebido de: ${r.residentName||""}`,14,y); y+=8; doc.text(`Endereço: ${enderecoCompleto(r.apartmentName)}`,14,y); y+=8; doc.text(`CEP: ${FIXOS.cep}`,14,y); y+=10; doc.text(`Referente a: ${r.referente}`,14,y); y+=8; doc.text(`Mês/Referência: ${(r.months||[]).map(m=>monthYearLabel(m,r.year)).join(", ")}`,14,y); y+=10; doc.setFont("helvetica","bold"); doc.text("Valores recebidos:",14,y); y+=8; doc.setFont("helvetica","normal"); const totalCondo=(r.condoPerMonth||0)*(r.months||[]).length; if(totalCondo>0){doc.text(`Condomínio: ${numberToMoney(totalCondo)}`,14,y);y+=8;} doc.setFont("helvetica","bold"); doc.text(`TOTAL: ${numberToMoney(r.paidNow||0)}`,14,y); y+=10; if((r.previousBalance||0)>0||(r.remainingBalance||0)>0){doc.setFont("helvetica","normal"); doc.text(`Saldo anterior: ${numberToMoney(r.previousBalance||0)}`,14,y); y+=8; doc.text(`Valor pago: ${numberToMoney(r.paidNow||0)}`,14,y); y+=8; doc.text(`Saldo restante: ${numberToMoney(r.remainingBalance||0)}`,14,y); y+=10;} doc.text(`${FIXOS.cidade}, dia ${r.issueDay} de ${MESES[r.issueMonth]} de ${r.issueYear}`,14,y); y+=10; doc.text(`Emitente: ${FIXOS.emitente}`,14,y); doc.save(`Recibo_${r.number}_${r.apartmentName}.pdf`);}
async function generateExpensePDF(e){if(!e)return; const {jsPDF}=window.jspdf; const doc=new jsPDF({unit:"mm",format:"a4"}); let y=header(doc,"COMPROVANTE DE DESPESA",18); doc.setFontSize(12); doc.text(`Data: ${String(e.day).padStart(2,"0")}/${String(e.month+1).padStart(2,"0")}/${e.year}`,14,y); y+=8; doc.text(`Categoria: ${e.category}`,14,y); y+=8; doc.text(`Descrição: ${e.description||""}`,14,y); y+=8; doc.setFont("helvetica","bold"); doc.text(`Valor: ${numberToMoney(e.value)}`,14,y); doc.save(`Despesa_${e.category}_${e.year}.pdf`);}
async function generateStatementPDF(kind){const {jsPDF}=window.jspdf; const doc=new jsPDF({unit:"mm",format:"a4"}); const logo=await loadLogoDataUrl(); const {year,month}=histFilter(); let title="PRESTAÇÃO DE CONTAS COMPLETA"; let rec=state.receipts, exp=state.expenses; if(kind==="mes"){if(month===null){alert("Selecione um mês no Histórico.");return;} title=`PRESTAÇÃO DE CONTAS — ${monthYearLabel(month,year)}`; rec=filteredReceipts(); exp=filteredExpenses();} if(kind==="ano"){title=`PRESTAÇÃO DE CONTAS — ${year}`; rec=state.receipts.filter(r=>r.year===year); exp=state.expenses.filter(e=>e.year===year);} const t=totals(rec,exp); let y=header(doc,title,addLogo(doc,logo)); doc.setFontSize(12); [`Saldo inicial: ${numberToMoney(state.settings.saldoInicial)}`,`Total recebido: ${numberToMoney(t.rec)}`,`Total despesas: ${numberToMoney(t.desp)}`,`Saldo esperado: ${numberToMoney(t.esp)}`,`Saldo real: ${numberToMoney(t.real)}`,`Diferença: ${numberToMoney(t.dif)} — ${t.dif>=0?"POSITIVO":"NEGATIVO"}`].forEach(line=>{doc.text(line,14,y);y+=8;}); y+=4; doc.setFont("helvetica","bold"); doc.text("Despesas:",14,y); y+=8; doc.setFont("helvetica","normal"); exp.forEach(e=>{const line=`${String(e.day).padStart(2,"0")}/${String(e.month+1).padStart(2,"0")}/${e.year} — ${e.category} — ${numberToMoney(e.value)} ${e.description||""}`; const lines=doc.splitTextToSize(line,180); doc.text(lines,14,y); y+=lines.length*5; if(y>275){doc.addPage(); y=20;}}); doc.save(title.replaceAll(" ","_").replaceAll("—","-")+".pdf");}
async function generateBatchReceiptsPDF(){const rec=filteredReceipts(); if(!rec.length)return alert("Nenhum recibo no filtro."); for(const r of rec) await generateReceiptPDF(r);}
function renderAll(){fillApartmentSelect();renderApartments();renderExpenses();renderHistory();renderPrestacao();handleApartmentChange();}
function wire(){qsa(".sidebtn").forEach(b=>b.onclick=()=>switchTab(b.dataset.tab)); ["#recApto","#recNome","#recAnoRef","#recDiaAtual","#recPagoAgora","#ckCondo"].forEach(s=>{qs(s).addEventListener("input",refreshReceiptPreview);qs(s).addEventListener("change",refreshReceiptPreview);}); qsa(".month-check").forEach(c=>c.onchange=refreshReceiptPreview); qs("#recApto").onchange=handleApartmentChange; qs("#btnGerarRecibo").onclick=saveReceipt; qs("#btnLimparRecibo").onclick=clearReceiptForm; qs("#btnAddDesp").onclick=saveExpense; qs("#btnLimparDesp").onclick=clearExpenseForm; qs("#despCat").onchange=setDefaultExpenseValue; qs("#btnAplicarFiltro").onclick=renderAll; qs("#btnRecalcular").onclick=()=>{recalcBalances(true);renderAll();}; qs("#btnSalvarCaixa").onclick=()=>{state.settings.saldoInicial=moneyToNumber(qs("#saldoInicial").value);state.settings.saldoReal=moneyToNumber(qs("#saldoReal").value);saveAll();renderPrestacao();}; qs("#btnPDFMes").onclick=()=>generateStatementPDF("mes"); qs("#btnPDFAno").onclick=()=>generateStatementPDF("ano"); qs("#btnPDFPrestacaoMes").onclick=()=>generateStatementPDF("mes"); qs("#btnPDFPrestacaoAno").onclick=()=>generateStatementPDF("ano"); qs("#btnPDFCompleta").onclick=()=>generateStatementPDF("completa"); qs("#btnPDFLote").onclick=generateBatchReceiptsPDF;}
(function boot(){migrate();loadDefaults();renderAll();wire();})();
