const MESES=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
const APTOS=["101","101 Fundos","201","201 Sala","201 Fundos","301","301 Sala","301 Fundos"];
const NOMES_PADRAO={
  "101":"Jaqueline C Ribeiro",
  "101 Fundos":"Catia Maria",
  "201":"Edmea de Melo",
  "201 Sala":"Danilo Reis E Silva",
  "201 Fundos":"",
  "301":"Marcia Valeria",
  "301 Sala":"Fernanda Telles",
  "301 Fundos":"Vagna Miranda"
};
const FIXOS={taxa:160,emitente:"Gabriel Brito Cirilo",rua:"Rua Glaziou, 30",bairro:"Pilares - RJ",cep:"20750-010",cidade:"Rio de Janeiro",isento:"101 Fundos",logo:"logo.png"};
const STORAGE={apartments:"glz_apartamentos_caixa_v4",receipts:"glz_receitas_caixa_v4",expenses:"glz_despesas_caixa_v4",seq:"glz_seq_caixa_v4",balances:"glz_saldos_caixa_v4",logo:"glz_logo_cache_v4"};
const state={apartments:[],receipts:[],expenses:[],balances:{},logoData:""};
function qs(s){return document.querySelector(s)}function qsa(s){return Array.from(document.querySelectorAll(s))}
function load(k,f){try{const r=localStorage.getItem(k);return r?JSON.parse(r):f}catch(e){return f}}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function moneyToNumber(v){if(v===undefined||v===null)return 0;let s=String(v).trim();if(!s)return 0;s=s.replace(/R\$/g,"").replace(/\s/g,"");if(s.includes(",")){s=s.replace(/\./g,"").replace(",",".")}return Number(s.replace(/[^\d.-]/g,""))||0}
function money(n){return (Number(n)||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function inputMoney(n){return (Number(n)||0).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})}
function uid(){return "id_"+Date.now()+"_"+Math.random().toString(16).slice(2)}function pad(n){return String(n).padStart(6,"0")}function now(){const d=new Date();return{day:d.getDate(),month:d.getMonth(),year:d.getFullYear()}}
function dateLabel(d,m,y){return String(d).padStart(2,"0")+"/"+String(m+1).padStart(2,"0")+"/"+y}function monthYear(m,y){return MESES[m]+"/"+y}
function initData(){
  let aps=load(STORAGE.apartments,[]);
  if(!aps.length){
    aps=APTOS.map(a=>({id:a,name:a,residentName:NOMES_PADRAO[a]||"",exempt:a===FIXOS.isento,role:a===FIXOS.isento?"Síndica / isento":""}));
  }else{
    APTOS.forEach(a=>{
      if(!aps.find(x=>x.id===a)) aps.push({id:a,name:a,residentName:NOMES_PADRAO[a]||"",exempt:a===FIXOS.isento,role:a===FIXOS.isento?"Síndica / isento":""});
    });
    aps.forEach(a=>{
      if(a.name===FIXOS.isento||a.id===FIXOS.isento){ a.exempt=true; a.role="Síndica / isento"; }
      if((!a.residentName || !String(a.residentName).trim()) && NOMES_PADRAO[a.id]) a.residentName=NOMES_PADRAO[a.id];
    });
  }
  state.apartments=aps;
  save(STORAGE.apartments,aps);
  state.receipts=load(STORAGE.receipts,[]);
  state.expenses=load(STORAGE.expenses,[]);
  state.balances=load(STORAGE.balances,{})
}
function setReceipts(v){state.receipts=v;save(STORAGE.receipts,v)}function setExpenses(v){state.expenses=v;save(STORAGE.expenses,v)}function setApartments(v){state.apartments=v;save(STORAGE.apartments,v)}function setBalances(v){state.balances=v;save(STORAGE.balances,v)}
function syncSeq(){let max=0;state.receipts.forEach(r=>{const n=Number(String(r.number||"").replace(/\D/g,""))||0;if(n>max)max=n});const cur=Number(localStorage.getItem(STORAGE.seq)||"0");if(max>cur)localStorage.setItem(STORAGE.seq,String(max))}
function nextNumber(){syncSeq();return pad((Number(localStorage.getItem(STORAGE.seq)||"0")||0)+1)}function consumeNumber(){syncSeq();const n=(Number(localStorage.getItem(STORAGE.seq)||"0")||0)+1;localStorage.setItem(STORAGE.seq,String(n));return pad(n)}
function fillMonths(sel,all=false){if(!sel)return;sel.innerHTML="";if(all){const o=document.createElement("option");o.value="-1";o.textContent="Todos";sel.appendChild(o)}MESES.forEach((m,i)=>{const o=document.createElement("option");o.value=i;o.textContent=m;sel.appendChild(o)})}
function fillDays(sel){if(!sel)return;sel.innerHTML="";for(let i=1;i<=31;i++){const o=document.createElement("option");o.value=i;o.textContent=i;sel.appendChild(o)}}
function fillAptos(){const sel=qs("#recApto");if(!sel)return;sel.innerHTML="";state.apartments.slice().sort((a,b)=>a.name.localeCompare(b.name)).forEach(a=>{const o=document.createElement("option");o.value=a.id;o.textContent=a.name+(a.exempt?" (isento)":"");sel.appendChild(o)})}
function apt(id){return state.apartments.find(a=>a.id===id)}
function keyYM(y,m){return y+"_"+m}function getBalance(y,m){return state.balances[keyYM(y,m)]||{initial:0,real:0}}
function saveBalanceInputs(){const y=Number(qs("#prestAno").value)||now().year;const m=Number(qs("#prestMes").value);state.balances[keyYM(y,m)]={initial:moneyToNumber(qs("#saldoInicial").value),real:moneyToNumber(qs("#saldoReal").value)};setBalances(state.balances);renderPrestacao();alert("Saldos salvos.")}
function loadBalanceInputs(){const y=Number(qs("#prestAno").value)||now().year;const m=Number(qs("#prestMes").value);const b=getBalance(y,m);qs("#saldoInicial").value=inputMoney(b.initial);qs("#saldoReal").value=inputMoney(b.real);renderPrestacao()}
function initTabs(){qsa(".sidebtn").forEach(btn=>btn.addEventListener("click",()=>{qsa(".sidebtn").forEach(b=>b.classList.remove("active"));btn.classList.add("active");qsa(".panel").forEach(p=>p.classList.add("hidden"));const p=qs("#tab-"+btn.dataset.tab);if(p)p.classList.remove("hidden")}))}
function updateNameFromApt(){const a=apt(qs("#recApto").value);if(!a)return;qs("#recNome").value=a.residentName||"";qs("#recValor").value=inputMoney(a.exempt?0:FIXOS.taxa);refreshPreview()}
function recData(){const a=apt(qs("#recApto").value);const t=now();const name=(qs("#recNome").value||"").trim();return{number:qs("#recNumero").value||nextNumber(),apartmentId:a?a.id:"",apartmentName:a?a.name:"",residentName:name||((a&&a.residentName)||""),displayName:name||((a&&a.residentName)||"")||((a&&a.name)||"Apartamento"),value:moneyToNumber(qs("#recValor").value),referente:qs("#recReferente").value,day:Number(qs("#recDia").value)||t.day,month:Number(qs("#recMes").value)||t.month,year:Number(qs("#recAno").value)||t.year,obs:(qs("#recObs").value||"").trim()}}
function refreshPreview(){const d=recData();const lines=[];lines.push(`RECIBO Nº ${d.number}`);lines.push("");lines.push(`Recebido de: ${d.displayName}`);lines.push(`Endereço: ${FIXOS.rua} — Apto ${d.apartmentName} / ${FIXOS.bairro}`);lines.push(`CEP: ${FIXOS.cep}`);lines.push("");lines.push(`Referente a: ${d.referente}`);lines.push(`Mês/Referência: ${monthYear(d.month,d.year)}`);lines.push("");lines.push(`Valor recebido: ${money(d.value)}`);if(d.obs)lines.push(`Observação: ${d.obs}`);lines.push("");lines.push(`${FIXOS.cidade}, dia ${d.day} de ${MESES[d.month]} de ${d.year}`);lines.push("");lines.push(`Emitente: ${FIXOS.emitente}`);qs("#recPreview").textContent=lines.join("\n")}
function saveReceipt(download=true){const d=recData();if(!d.apartmentName){alert("Selecione um apartamento.");return}if(d.value<=0){alert("Digite o valor recebido.");return}const number=consumeNumber();const item={...d,id:uid(),number,createdAt:Date.now()};const aps=state.apartments.slice();const a=aps.find(x=>x.id===item.apartmentId);if(a&&qs("#recNome").value.trim()){a.residentName=qs("#recNome").value.trim();setApartments(aps)}setReceipts([...state.receipts,item]);qs("#recNumero").value=nextNumber();qs("#recObs").value="";renderAll();if(download)generateReceiptPDF(item)}
function renderApartments(){const tb=qs("#tbodyApartamentos");if(!tb)return;tb.innerHTML="";state.apartments.slice().sort((a,b)=>a.name.localeCompare(b.name)).forEach(a=>{const tr=document.createElement("tr");const obs=a.exempt?"Síndica / isento":"Normal";tr.innerHTML=`<td>${a.name}</td><td><input data-apname="${a.id}" value="${a.residentName||""}" placeholder="Nome opcional"></td><td>${a.exempt?"Sim":"Não"}</td><td>${obs}</td><td class="actions"><button class="linkbtn" data-saveap="${a.id}">Salvar</button></td>`;tb.appendChild(tr)});tb.querySelectorAll("[data-saveap]").forEach(b=>b.addEventListener("click",()=>{const id=b.dataset.saveap;const aps=state.apartments.slice();const a=aps.find(x=>x.id===id);if(a){a.residentName=tb.querySelector(`[data-apname="${id}"]`).value.trim();setApartments(aps);fillAptos();renderApartments();updateNameFromApt();alert("Nome salvo.")}}))}
function addExpense(){const v=moneyToNumber(qs("#despValor").value);if(v<=0){alert("Digite o valor da despesa.");return}const item={id:uid(),day:Number(qs("#despDia").value),month:Number(qs("#despMes").value),year:Number(qs("#despAno").value),category:qs("#despCat").value,description:qs("#despDesc").value.trim(),value:v,createdAt:Date.now()};setExpenses([...state.expenses,item]);qs("#despValor").value="";qs("#despDesc").value="";renderAll()}
function renderExpenses(){const tb=qs("#tbodyDespesas");if(!tb)return;tb.innerHTML="";state.expenses.slice().sort((a,b)=>b.createdAt-a.createdAt).forEach(e=>tb.appendChild(expRow(e)))}
function expRow(e){const tr=document.createElement("tr");tr.innerHTML=`<td>${dateLabel(e.day,e.month,e.year)}</td><td>${e.category}</td><td>${e.description||""}</td><td>${money(e.value)}</td><td class="actions"><button class="linkbtn" data-editexp="${e.id}">Editar</button><button class="linkbtn danger" data-delexp="${e.id}">Excluir</button></td>`;return tr}
function filters(){const y=Number(qs("#histAno").value)||null;const mr=Number(qs("#histMes").value);return{year:y,month:mr>=0?mr:null}}
function filteredReceipts(year,month){return state.receipts.filter(r=>(!year||r.year===year)&&(month===null||r.month===month))}function filteredExpenses(year,month){return state.expenses.filter(e=>(!year||e.year===year)&&(month===null||e.month===month))}
function totals(year,month){const rec=filteredReceipts(year,month),exp=filteredExpenses(year,month);return{received:rec.reduce((s,r)=>s+Number(r.value||0),0),spent:exp.reduce((s,e)=>s+Number(e.value||0),0),rec,exp}}
function renderHistory(){const {year,month}=filters();const t=totals(year,month);qs("#histTotais").innerHTML=`<div><b>Total recebido:</b> ${money(t.received)}</div><div><b>Total despesas:</b> ${money(t.spent)}</div><div><b>Resultado:</b> ${money(t.received-t.spent)}</div>`;const rb=qs("#tbodyReceitas");rb.innerHTML="";t.rec.slice().sort((a,b)=>b.createdAt-a.createdAt).forEach(r=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${r.number}</td><td>${dateLabel(r.day,r.month,r.year)}</td><td>${r.apartmentName}</td><td>${r.displayName||r.residentName||r.apartmentName}</td><td>${r.referente}</td><td>${money(r.value)}</td><td class="actions"><button class="linkbtn" data-pdfrec="${r.id}">PDF</button><button class="linkbtn" data-editrec="${r.id}">Editar</button><button class="linkbtn danger" data-delrec="${r.id}">Excluir</button></td>`;rb.appendChild(tr)});const eb=qs("#tbodyHistDespesas");eb.innerHTML="";t.exp.slice().sort((a,b)=>b.createdAt-a.createdAt).forEach(e=>eb.appendChild(expRow(e)));wireDynamicButtons()}
function renderPrestacao(){const y=Number(qs("#prestAno").value)||now().year;const m=Number(qs("#prestMes").value);const b=getBalance(y,m);const t=totals(y,m);const expected=b.initial+t.received-t.spent;const diff=b.real-expected;const cls=diff>=0?"positivo":"negativo";const label=diff>=0?"🟢 POSITIVO — sobrou":"🔴 NEGATIVO — falta";qs("#prestResumo").innerHTML=`<div class="resumoCard"><div class="label">Saldo inicial</div><div class="value">${money(b.initial)}</div></div><div class="resumoCard"><div class="label">Total recebido</div><div class="value positivo">${money(t.received)}</div></div><div class="resumoCard"><div class="label">Total despesas</div><div class="value negativo">${money(t.spent)}</div></div><div class="resumoCard"><div class="label">Saldo esperado</div><div class="value">${money(expected)}</div></div><div class="resumoCard"><div class="label">Saldo real</div><div class="value">${money(b.real)}</div></div><div class="resumoCard"><div class="label">Diferença</div><div class="value ${cls}">${money(diff)}</div></div><div class="resumoCard"><div class="label">Situação</div><div class="value ${cls}">${label}</div></div><div class="resumoCard"><div class="label">Resumo</div><div class="value">${diff>=0?"Sobrou "+money(diff):"Falta "+money(Math.abs(diff))}</div></div>`}
function wireDynamicButtons(){document.querySelectorAll("[data-delrec]").forEach(b=>b.onclick=()=>{if(confirm("Excluir este recibo/receita?")){setReceipts(state.receipts.filter(r=>r.id!==b.dataset.delrec));renderAll()}});document.querySelectorAll("[data-pdfrec]").forEach(b=>b.onclick=()=>{const r=state.receipts.find(x=>x.id===b.dataset.pdfrec);if(r)generateReceiptPDF(r)});document.querySelectorAll("[data-editrec]").forEach(b=>b.onclick=()=>editReceipt(b.dataset.editrec));document.querySelectorAll("[data-delexp]").forEach(b=>b.onclick=()=>{if(confirm("Excluir esta despesa?")){setExpenses(state.expenses.filter(e=>e.id!==b.dataset.delexp));renderAll()}});document.querySelectorAll("[data-editexp]").forEach(b=>b.onclick=()=>editExpense(b.dataset.editexp))}
function editReceipt(id){const r=state.receipts.find(x=>x.id===id);if(!r)return;const novo=prompt("Novo valor recebido:",inputMoney(r.value));if(novo===null)return;const val=moneyToNumber(novo);if(val<=0){alert("Valor inválido.");return}r.value=val;const nome=prompt("Nome do morador/proprietário (opcional):",r.residentName||"");if(nome!==null){r.residentName=nome.trim();r.displayName=nome.trim()||r.apartmentName}setReceipts(state.receipts);renderAll()}
function editExpense(id){const e=state.expenses.find(x=>x.id===id);if(!e)return;const novo=prompt("Novo valor da despesa:",inputMoney(e.value));if(novo===null)return;const val=moneyToNumber(novo);if(val<=0){alert("Valor inválido.");return}e.value=val;const desc=prompt("Descrição:",e.description||"");if(desc!==null)e.description=desc.trim();setExpenses(state.expenses);renderAll()}
async function logoData(){if(state.logoData)return state.logoData;const c=localStorage.getItem(STORAGE.logo);if(c){state.logoData=c;return c}try{const res=await fetch(FIXOS.logo,{cache:"no-store"});const blob=await res.blob();const data=await new Promise((ok,err)=>{const rd=new FileReader();rd.onload=()=>ok(rd.result);rd.onerror=err;rd.readAsDataURL(blob)});state.logoData=data;localStorage.setItem(STORAGE.logo,data);return data}catch(e){return""}}
function pdfHead(doc,title){doc.setFont("helvetica","bold");doc.setFontSize(14);doc.text(title,14,18);doc.setFont("helvetica","normal");doc.setFontSize(10);doc.text(`${FIXOS.rua} / ${FIXOS.bairro} — CEP ${FIXOS.cep}`,14,25);doc.line(14,29,196,29);return 40}
async function generateReceiptPDF(r){const {jsPDF}=window.jspdf||{};if(!jsPDF){alert("PDF não carregou. Verifique a internet e tente novamente.");return}const doc=new jsPDF({unit:"mm",format:"a4"});let y=pdfHead(doc,`RECIBO Nº ${r.number}`);doc.setFontSize(12);doc.text(`Recebido de: ${r.displayName||r.residentName||r.apartmentName}`,14,y);y+=8;doc.text(`Endereço: ${FIXOS.rua} — Apto ${r.apartmentName} / ${FIXOS.bairro}`,14,y);y+=8;doc.text(`CEP: ${FIXOS.cep}`,14,y);y+=10;doc.text(`Referente a: ${r.referente}`,14,y);y+=8;doc.text(`Mês/Referência: ${monthYear(r.month,r.year)}`,14,y);y+=10;doc.setFont("helvetica","bold");doc.text(`Valor recebido: ${money(r.value)}`,14,y);y+=12;doc.setFont("helvetica","normal");if(r.obs){doc.text(`Observação: ${r.obs}`,14,y);y+=8}doc.text(`${FIXOS.cidade}, dia ${r.day} de ${MESES[r.month]} de ${r.year}`,14,y);y+=12;doc.text(`Emitente: ${FIXOS.emitente}`,14,y);doc.save(`Recibo_${r.number}_${r.apartmentName}.pdf`)}
async function statementPDF(scope){const {jsPDF}=window.jspdf||{};if(!jsPDF){alert("PDF não carregou.");return}const y0=scope==="year"?Number(qs("#prestAno").value):Number(qs("#prestAno").value);const m=Number(qs("#prestMes").value);let rec,exp,title,b={initial:0,real:0};if(scope==="year"){rec=state.receipts.filter(r=>r.year===y0);exp=state.expenses.filter(e=>e.year===y0);title=`PRESTAÇÃO DE CONTAS — ${y0}`}else if(scope==="all"){rec=state.receipts;exp=state.expenses;title="PRESTAÇÃO DE CONTAS COMPLETA"}else{rec=filteredReceipts(y0,m);exp=filteredExpenses(y0,m);b=getBalance(y0,m);title=`PRESTAÇÃO DE CONTAS — ${monthYear(m,y0)}`}const received=rec.reduce((s,r)=>s+Number(r.value||0),0),spent=exp.reduce((s,e)=>s+Number(e.value||0),0),expected=b.initial+received-spent,diff=b.real-expected;const doc=new jsPDF({unit:"mm",format:"a4"});let y=pdfHead(doc,title);doc.setFontSize(12);doc.text(`Saldo inicial: ${money(b.initial)}`,14,y);y+=8;doc.text(`Total recebido: ${money(received)}`,14,y);y+=8;doc.text(`Total despesas: ${money(spent)}`,14,y);y+=8;doc.text(`Saldo esperado: ${money(expected)}`,14,y);y+=8;doc.text(`Saldo real: ${money(b.real)}`,14,y);y+=8;doc.text(`Diferença: ${money(diff)} — ${diff>=0?"POSITIVO":"NEGATIVO"}`,14,y);y+=12;doc.setFont("helvetica","bold");doc.text("Receitas:",14,y);y+=7;doc.setFont("helvetica","normal");doc.setFontSize(10);rec.forEach(r=>{const line=`${dateLabel(r.day,r.month,r.year)} — ${r.apartmentName} — ${r.displayName||r.apartmentName} — ${r.referente} — ${money(r.value)}`;const sp=doc.splitTextToSize(line,180);doc.text(sp,14,y);y+=sp.length*5;if(y>275){doc.addPage();y=20}});y+=6;doc.setFont("helvetica","bold");doc.text("Despesas:",14,y);y+=7;doc.setFont("helvetica","normal");exp.forEach(e=>{const line=`${dateLabel(e.day,e.month,e.year)} — ${e.category} — ${money(e.value)}${e.description?" — "+e.description:""}`;const sp=doc.splitTextToSize(line,180);doc.text(sp,14,y);y+=sp.length*5;if(y>275){doc.addPage();y=20}});doc.save(title.replace(/\s+/g,"_").replace(/[\/]/g,"-")+".pdf")}
function renderAll(){renderApartments();renderExpenses();renderHistory();renderPrestacao();refreshPreview()}
function defaults(){const t=now();fillAptos();fillDays(qs("#recDia"));fillMonths(qs("#recMes"));fillDays(qs("#despDia"));fillMonths(qs("#despMes"));fillMonths(qs("#prestMes"));fillMonths(qs("#histMes"),true);qs("#recNumero").value=nextNumber();qs("#recDia").value=t.day;qs("#recMes").value=t.month;qs("#recAno").value=t.year;qs("#recValor").value=inputMoney(FIXOS.taxa);qs("#despDia").value=t.day;qs("#despMes").value=t.month;qs("#despAno").value=t.year;qs("#prestMes").value=t.month;qs("#prestAno").value=t.year;qs("#histMes").value="-1";qs("#histAno").value=t.year;loadBalanceInputs();updateNameFromApt()}
function wire(){initTabs();["#recApto","#recNome","#recValor","#recReferente","#recDia","#recMes","#recAno","#recObs"].forEach(s=>{const e=qs(s);if(e){e.addEventListener("input",refreshPreview);e.addEventListener("change",refreshPreview)}});qs("#recApto").addEventListener("change",updateNameFromApt);qs("#btnSalvarRecibo").addEventListener("click",()=>saveReceipt(true));qs("#btnSalvarSemPdf").addEventListener("click",()=>saveReceipt(false));qs("#btnAddDesp").addEventListener("click",addExpense);qs("#btnFiltrarHist").addEventListener("click",renderHistory);qs("#btnSalvarSaldos").addEventListener("click",saveBalanceInputs);qs("#prestMes").addEventListener("change",loadBalanceInputs);qs("#prestAno").addEventListener("input",loadBalanceInputs);qs("#btnPdfMensal").addEventListener("click",()=>statementPDF("month"));qs("#btnPdfAnual").addEventListener("click",()=>statementPDF("year"));qs("#btnPdfCompleta").addEventListener("click",()=>statementPDF("all"));["#despCat"].forEach(s=>{const e=qs(s);e.addEventListener("change",()=>{if(e.value==="Zelador (Tião)")qs("#despValor").value="250,00";if(e.value==="Material limpeza")qs("#despValor").value="50,00"})})}
window.addEventListener("error",e=>{console.error(e.error||e.message);alert("O sistema encontrou um erro no JavaScript. Me envie um print do console se continuar.")});
(function boot(){initData();defaults();wire();renderAll()})();
